### ISSUE TITLE
Permutation entropy

### ISSUE THREAD

**Issue by tkf** [JuliaDynamics/ChaosTools.jl#18] opened 2018-01-26 09:59 UTC
Hi, I implemented the permutation entropy ([Bandt & Pompe, 2002](http://doi.org/10.1103/PhysRevLett.88.174102)).  Do you want add it to ChaosTools.jl?  Let me know if you want a PR.  Here is a demo: https://gist.github.com/tkf/31cb31564dc4f61c085d013656f1a9e9

```julia
function permutation_entropy(
        time_series::Array{T, 1}, ord::O, sampling_interval::S = 1;
        base = Base.e) where {T, O <: Integer, S <: Integer}
    n = length(time_series)
    perms = hcat(Combinatorics.permutations(O(1):ord)...)
    nperm = size(perms)[2]
    ptype = collect(O(1):ord)
    count = zeros(UInt64, nperm)

    for t in 1:n-sampling_interval * ord
        sample = time_series[t:sampling_interval:t+sampling_interval * (ord-1)]
        sortperm!(ptype, sample)
        for i in 1:nperm
            if perms[:, i] == ptype
                count[i] += 1
                break
            end
        end
    end

    nonzero = collect(c for c in count if c != 0)
    p = nonzero / sum(nonzero)
    return - sum(p .* log.(base, p))
end
```

I think this is not an optimal implementation though.  I just wrote it as a quick exercise a while ago.  Besides a few Julia related improvements (like using `@views`), I think the inner most loop that searches the permutation can be improved, using the fact that the permutation counter `perms` is sorted and maybe also by using better data structure.

Also, I'm not a data analysis guy so I don't know if this method is relevant these days.

Anyway, what do you think?  It's good to add it?

**Comment by Datseris** [comment] 2018-01-26 10:13
> I implemented the permutation entropy (Bandt & Pompe, 2002). Do you want add it to ChaosTools.jl? 

of course!!! Why not! You can put it in `dimensions/entropies.jl`. Make sure to leave the option "allow commit from owners" or something like that, on, so I can also do commits for e.g. documentation strings. If you want forking and pushing access before starting the PR just ask. For me it is always heplful.

Off topic: the syntax `function f{T}(stuf::T)` is going away on Julia 0.7, you should start using `function f(stuff::T) where {T}` to avoid having to re-write stuff (in general not just for this discussion).

> Also, I'm not a data analysis guy so I don't know if this method is relevant these days.

Doesn't matter if it is not a hot topic, it is a valid, useful, and published in a very high raking journal. I think it is a great benefit if you are willing to contribute it and I appreciate it (along with anyone else using this package I am sure).

I will write documentation for it based on your example notebook, if it is contributed.

> I think this is not an optimal implementation though. I just wrote it as a quick exercise a while ago. Besides a few Julia related improvements (like using @views), I think the inner most loop that searches the permutation can be improved, using the fact that the permutation counter perms is sorted and maybe also by using better data structure.

Yeah, here comes the hard part. Unfortunately I am not *that* good with Julia to do performance improvements without having code to run. I can check the performance part over the weekend. The certain part is to just do `sample =@view time_series[t:sampling_interval:t+sampling_interval * (ord-1)]`. However, like you suggested, I am sure we can improve this further, but this is a secondary concern. Once this is merged and all is good I can work on a performance branch.

A primary "concern" is: If this is to be merged, it also must have tests. I think it is clear from the notebook that the method works perfectly fine, since you reproduce the PRL results, but unfortunately one has to also code the tests. I can do this once you open the PR.

**Comment by Datseris** [comment] 2018-01-26 10:18
On another note, there is no gain to have `O(1):ord` and to introduce the type `O`. I think without a worry you can use the `Int` `1` and Julia will take care of the rest.

**Comment by Datseris** [comment] 2018-01-26 11:13
also this is not necessary: `nonzero = collect(c for c in count if c != 0)`
since you `sum(nonzero)`, summing over additional zero elements makes no difference in the end result. However with `collect` you are creatting one more array, which is costly.

**Comment by tkf** [comment] 2018-01-27 09:43
Hey, thanks for the comments.  Let's continue the code review at #20.

**Closed** 2018-01-27 12:29 UTC
