### ISSUE TITLE
Speedup: possibility to calculate not all Lyapunov exponents but only few

### ISSUE THREAD

**Issue by RainerEngelken** [JuliaDynamics/ChaosTools.jl#29] opened 2018-02-10 21:18 UTC
Just add a parameter for the desired number of Lyapunov exponents to be calculated. As the orthonormalization scales with order n*d^2 where n is the number of degrees of freedom and d is the number of Lyapunov exponents to be calculated, this can result in a speedup of order (n/d)^2, when only the first d Lyapunov exponents are calculated. So in a system of 10^4 equations, when you just need the first 10 Lyapunov exponents, this would be a speedup factor of 10^6.

**Comment by Datseris** [comment] 2018-02-10 21:22
duplicate of #7

**Closed by Datseris** 2018-02-10 21:22 UTC

**Comment by RainerEngelken** [comment] 2018-02-10 21:23
sorry, haven't seen that.

**Comment by Datseris** [comment] 2018-02-10 21:24
No reason to apologize!
